[flags]
IsContainer = "Container"
ForceUse = "Force Use"
MultiUse = "Multi Use"
IsFluidContainer = "Fluid Container"
IsFluid = "Fluid"
IsUnpassable = "Unpassable"
IsUnmoveable = "Unmoveable"
BlockMissile = "Block Missile"
BlockPathfind = "Block Pathfinder"
Pickupable = "Pickupable"
Rotatable = "Rotatable"
IsLyingObject = "Lying Object"
IsFullGround = "Full Ground"
Wrappable = "Wrappable"
Unwrappable = "Unwrappable"
FloorChange = "Floor Change"
