[flags]
IsContainer = "Container"
ForceUse = "Force Use"
MultiUse = "Multi Use"
IsFluidContainer = "Fluid Container"
IsFluid = "Fluid"
IsUnpassable = "Unpassable"
IsUnmoveable = "Unmoveable"
BlockMissile = "Block Missile"
BlockPathfind = "Block Pathfinder"
Pickupable = "Pickupable"
Rotatable = "Rotatable"
IsLyingObject = "Lying Object"
IsFullGround = "Full Ground"
NoMoveAnimation = "No Move Animation"
Hangable = "Hangable"
IsHorizontal = "Hook East"
IsVertical = "Hook South"
DontHide = "Don't Hide"
IsTranslucent = "Translucent"
IgnoreLook = "Ignore Look"
Usable = "Useable"
Wrappable = "Wrappable"
Unwrappable = "Unwrappable"
BottomEffect = "Top Effect"
